name: Playground

on:
  push:
    branch: [master, dev]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.ref }} | sed -e "s#refs/heads/##g"